name: learning_transformer
channels:
- defaults
- pytorch
dependencies:
- python=3.10
# - cudatoolkit=12.1
- numpy
- pip
- pip:
  - torch
  - torchvision
  - tqdm==4.64.0
  - git+https://github.com/ildoonet/pytorch-gradual-warmup-lr.git
  - opencv-python==4.6.0.66
  - h5py==3.6.0
  - wandb==0.12.18
  - prettytable
  - efficientnet-pytorch
  - warmup-scheduler
  - lmdb 
  - vit-pytorch
  - positional-encodings
  - matplotlib